name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Unit Tests
        working-directory: tests 
        run: |
          echo "Run Tests"
