name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  version:
    name: Generate version
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.next_version.outputs.new_tag }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Bump version
        id: next_version
        uses: anothrNick/github-tag-action@1.40.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRY_RUN: true

  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      GITHUB_OWNER: project-manager-testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v1.0.0
        with:
          gotestsum_version: 1.8.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Download Go Modules
        working-directory: test
        run: |
          go mod download

      - name: Run Unit Tests
        working-directory: test
        run: |
          gotestsum --format testname -- -run TestUT_ -v

      - name: Run Integration Tests
        working-directory: test
        run: |
          gotestsum --format testname -- -run TestIT_ -v

  tag:
    name: Tag version
    runs-on: ubuntu-latest
    needs: [tests]
    if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Tag version
        uses: anothrNick/github-tag-action@1.40.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CUSTOM_TAG: ${{ needs.version.outputs.new_version }}
