name: Terraform

on:
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update Pull Request
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const plan1 = '### TODO1'
            const plan2 = '### TODO2\nHello World'
            const plan3 = '### TODO3\n"Hello World"'

            const output = `### ⚠️ Terraform Documentation Outdated
            #### Update \`./README.md\` 📖
            <details><summary>Show Markdown</summary>
            \`\`\`
            ## Title1
            ### Subtitle1
            ${plan1}
            \`\`\`
            </details>

            #### Update \`./examples/basic-github-repository/README.md\` 📖
            <details><summary>Show Markdown</summary>
            \`\`\`
            ## Title2
            ### Subtitle2
            $plan2
            \`\`\`
            </details>

            #### Update \`./test/fixtures/basic-repository/README.md\` 📖
            <details><summary>Show Markdown</summary>
            \`\`\`
            ## Title3
            ### Subtitle3
            $plan3
            \`\`\`
            </details>
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      # - name: Render terraform docs inside the README.md and push changes back to PR branch
      #   uses: terraform-docs/gh-actions@v1.0.0
      #   with:
      #     find-dir: . # INPUT_FIND_DIR
      #     output-file: README.md #INPUT_OUTPUT_FILE
      #     output-method: print # INPUT_OUTPUT_METHOD
      #     git-push: 'false' # INPUT_GIT_PUSH
